componentScriptContent: 
  - xmlizable: 
    - â†‘classname: com.twinsoft.convertigo.beans.common.FormatedContent
    - com.twinsoft.convertigo.beans.common.FormatedContent: 
      â†’: |
        /*Begin_c8o_AppImport*/
        /*End_c8o_AppImport*/
        /*Begin_c8o_AppDeclaration*/
        	/*End_c8o_AppDeclaration*/
        /*Begin_c8o_AppConstructor*/
        		/*End_c8o_AppConstructor*/
        /*Begin_c8o_AppInitialization*/
                        /* Uncomment the following lines to enable the i18n feature.
                         * You should add a json per language in the assets/i18n folder. */
                        translate.setDefaultLang('en');
                        translate.use(translate.getBrowserLang());
                        
                        /* Uncomment the following lines to enable the custom status bar color. */
                        // statusBar.overlaysWebView(false);
                        // statusBar.backgroundColorByHexString("#000000");
                        // statusBar.styleBlackOpaque();
        			/*End_c8o_AppInitialization*/
        /*Begin_c8o_AppFunction*/
        	/*End_c8o_AppFunction*/
        
tplProjectName: mobilebuilder_tpl_7_9_0
â†“Menu [mobile.components.UIDynamicMenu-1500890597895]: ðŸ— mobileMenus/Menu.yaml
â†“SetLocalStorage [mobile.components.UIActionStack-1671009156063]: ðŸ— mobileSharedActions/SetLocalStorage.yaml
â†“ngxTagInputCustomC8oForms [mobile.components.UISharedComponent-1671128004246]: ðŸ— mobileSharedComponents/ngxTagInputCustomC8oForms.yaml
â†“Page [mobile.components.PageComponent-1500538678074]: ðŸ— mobilePages/Page.yaml
â†“Theme [mobile.components.UITheme-1491635018260]: 
  comment: Global color themes can be customized here
  styleContent: 
    - xmlizable: 
      - â†‘classname: com.twinsoft.convertigo.beans.common.FormatedContent
      - com.twinsoft.convertigo.beans.common.FormatedContent: 
        â†’: |
          '// Ionic Variables and Theming. For more info, please see:
          // http://ionicframework.com/docs/v2/theming/ 
          $font-path: "../assets/fonts";
          
          @import "ionic.globals";
          
          
          // Shared Variables
          // --------------------------------------------------
          // To customize the look and feel of this app, you can override
          // the Sass variables found in Ionic''s source scss files.
          // To view all the possible Ionic variables, see:
          // http://ionicframework.com/docs/v2/theming/overriding-ionic-variables/
          
          
          
          
          // Named Color Variables
          // --------------------------------------------------
          // Named colors makes it easy to reuse colors on various components.
          // It''s highly recommended to change the default colors
          // to match your app''s branding. Ionic uses a Sass map of
          // colors so you can add, rename and remove colors as needed.
          // The "primary" color is the only required color in the map.
          
          $colors: (
                  primary:    #387ef5,
                  secondary:  #32db64,
          		orange: 	#ff8206,
          		green: 	green,
          		lightgreen: lightgreen,
                  danger:     #f53d3d,
                  light:      #f4f4f4,
                  dark:       #222
          );
          
          
          // App iOS Variables
          // --------------------------------------------------
          // iOS only Sass variables can go here
          
          
          
          
          // App Material Design Variables
          // --------------------------------------------------
          // Material Design only Sass variables can go here
          
          
          
          
          // App Windows Variables
          // --------------------------------------------------
          // Windows only Sass variables can go here
          
          
          
          
          // App Theme
          // --------------------------------------------------
          // Ionic apps can have different themes applied, which can
          // then be future customized. This import comes last
          // so that the above variables are used and Ionic''s
          // default are overridden.
          
          @import "ionic.theme.default";
          
          
          // Ionicons
          // --------------------------------------------------
          // The premium icon font for Ionic. For more info, please see:
          // http://ionicframework.com/docs/v2/ionicons/
          
          @import "ionic.ionicons";
          
          
          // Fonts
          // --------------------------------------------------
          
          @import "roboto";
          @import "noto-sans";'
â†“Style [mobile.components.UIStyle-1491635462437]: 
  comment: You can add some global application styles here
  styleContent: 
    - xmlizable: 
      - â†‘classname: com.twinsoft.convertigo.beans.common.FormatedContent
      - com.twinsoft.convertigo.beans.common.FormatedContent: 
        â†’: |
          '.content {
          	/* add some styling CSS rules here for the body of your app
          	   for example,
          	 		background-color: your color; 
          	 		background-image: url(some background image);
          	*/
          }
          
          .toolbar-background {
          	/* add some styling CSS rules here for the Headers and Footers
          	   for example,
          	 		background-color: your color; 
          	*/
          }
          
          .classNoSpaces{
          	padding-left:0 !important;
          	ion-icon{
          		margin-right: 0 !important;
          	}
          	.item-inner{
          		margin-left: 5px !important;
          		padding-right: 0 !important;
          	}
          }
          .classNoSpaces2{
          	background-color:transparent;
          	padding-left:0 !important;
          	ion-icon{
          		margin-right: 0 !important;
          		margin-top: 0 !important;
          		margin-bottom: 0 !important;
          	}
          	.item-inner{
          		margin-left: 5px !important;
          		padding-right: 0 !important;
          		max-height:19px !important;
          	}
          	ion-label{
          		background-color:transparent;
          		margin-top: 0 !important;
          		margin-bottom: 0 !important;
          	}
          }'
â†“States [mobile.components.UIStyle-1670950069174]: 
  styleContent: 
    - xmlizable: 
      - â†‘classname: com.twinsoft.convertigo.beans.common.FormatedContent
      - com.twinsoft.convertigo.beans.common.FormatedContent: 
        â†’: |
          '.state-ok-win {
          	background-color: color($colors, lightgreen);
          }
          
          .state-ok-win, .state-ok {
          	color: color($colors, green);
          	ion-label{
          		color: black;
          		font-weight: bold;
          	}
          }
          
          .state-deleted {
          	color: color($colors, orange);
          	ion-label{
          		color: black;
          		font-weight: bold;
          	}
          }
          
          .state-missing {
          	color: color($colors, danger);
          	ion-label{
          		color: black;
          		font-weight: bold;
          	}
          }
          
          .rev>ion-card {
          	overflow-wrap: anywhere;
          }
          
          .rev.state-missing, .rev.state-deleted, .rev.state-ok, .rev.state-ok-win {
          	border: solid 3px;
          	border-radius: 7.5px;
          	margin: 1px;
          }
          
          .rev.state-ok, .rev.state-ok-win {
          	cursor: pointer;
          }'
â†“customIcons [mobile.components.UIStyle-1671138314674]: 
  styleContent: 
    - xmlizable: 
      - â†‘classname: com.twinsoft.convertigo.beans.common.FormatedContent
      - com.twinsoft.convertigo.beans.common.FormatedContent: 
        â†’: |
          '// Custom icons
          // Overriding the ion-icon behavior
          // All custom icons will start with "custom-" prefix
          ion-icon {
              &[class*="custom-"] {
                  // Instead of using the font-based icons
                  // We''re applying SVG masks
                  mask-size: contain;
                  mask-position: 50% 50%;
                  mask-repeat: no-repeat;
                  background: currentColor;
          		width: 1.2rem;
          		height: 1.2rem;
              }
              // custom icons
              &[class*="custom-bdd"] {
                  mask-image: url(../assets/images/icons/server.svg);
              }
          }
          
          '